Fix base-image resultion error
Currently the build of base-images fails due to potential dependency
confusion. The patch resolves the issue by providing a full qualified
image name.

Error message:
```
STEP 1: FROM nginx:alpine
Error: error creating build container: short-name resolution enforced but cannot prompt without a TTY
```

Reference:
https://github.com/containers/podman/issues/10492